# Generated by Django 5.2 on 2025-04-06 05:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_icons/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='course_images/'),
        ),
    ]
